language: php

php:
    - 5.4
    - 5.5
    - hhvm

services:
    - mysql


script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
    - app/console doctrine:database:create --env=test --no-interaction --quiet
    - app/console doctrine:migrations:migrate --env=test --no-interaction --quiet
    - app/console cache:warmup --env=test --quiet

script:
    #- ./bin/phpspec run -fpretty --verbose
    - phpunit --configuration phpunit.xml

matrix:
    allow_failures:
    - php: hhvm
