sudo: required

language: php

php:
    - 5.5
    - 7.0
    - hhvm

services:
    - mysql

before_script:
    - cp app/config/parameters.yml.travis app/config/parameters.yml
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
    - bin/console doctrine:database:create --env=test --no-interaction --quiet

script:
    - phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
    allow_failures:
    - php: hhvm
