version: "2"

services:
  web:
    container_name: symfony_web 
    extends:
      file: ./../docker/centos/base-machine.yml
      service: web
    volumes:
      - ./web/vhost.d/:/etc/httpd/vhost.d/
      - /var/www/git/:/var/www/git/
  db:
    container_name: symfony_db
    extends:
      file: ./../docker/centos/base-machine.yml
      service: db 
    volumes:
      - db_symfony:/var/lib/mysql
      - db_symfony_log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor 
      MYSQL_USER: root
volumes:
  db_symfony : {}
  db_symfony_log: {}
